apiVersion: apps/v1                 # API version for Deployment (apps group)

kind: Deployment                   # Defines this resource as a Deployment (manages pods)

metadata:
  name: flask-app                  # Name of the Deployment
  namespace: poc-namespace         # Namespace where this Deployment is created

spec:
  replicas: 2                      # Number of pod replicas to run (for scalability & high availability)

  selector:
    matchLabels:
      app: flask-app               # Selects pods with this label (must match template labels)

  template:                        # Template used to create pods
    metadata:
      labels:
        app: flask-app             # Label assigned to pods (used by Service to identify pods)

    spec:
      containers:
      - name: flask-container      # Name of the container inside the pod

        image: flask-app           # Docker image name (built locally in Minikube)
        imagePullPolicy: Never     # Do not pull from Docker Hub (use local image only)

        ports:
          - containerPort: 5000    # Port exposed by container (Flask app runs on 5000)

        envFrom:
        - configMapRef:
            name: app-config       # Loads environment variables from ConfigMap

        livenessProbe:             # Checks if container is alive (restarts if it fails)
          httpGet:
            path: /health          # Endpoint to check health
            port: 5000             # Port to check
          initialDelaySeconds: 5   # Wait 5 seconds before first check
          periodSeconds: 10        # Check every 10 seconds

        readinessProbe:            # Checks if container is ready to serve traffic
          httpGet:
            path: /health          # Same health endpoint
            port: 5000             # Port to check
          initialDelaySeconds: 5   # Wait before first readiness check
          periodSeconds: 10        # Check interval
